services:
 app:
   image: rss-tecmundo-node
   build:
     context: .
     dockerfile: Dockerfile
   ports:
     - "80:3000"  
   environment:
     - .env
   volumes:
     - .:/usr/src/app
     - ~/.aws:/root/.aws
   restart: always